---
- hosts: c1,c2,c3
#- remote_user: vagrant
  become: true
  tasks:
    - name: Update KERNEL in 3 CentOS for DELL demonstration
      yum:
        name: "kernel"
        state: latest
        update_cache: yes
    - name: Restart system to reboot to newest kernel
      shell: "sleep 5 && reboot"
      async: 1
      poll: 0
    - name: Wait for 10 seconds
      pause:
       seconds: 10
    - name: Wait for the system to reboot
      wait_for_connection:
        connect_timeout: 10
        sleep: 5
        delay: 5
        timeout: 20
    - name: install epel-release
      yum:
        name: epel-release
        state: latest
